### get api
GET http://localhost:8000/api/v1

### get api send the id with the
POST http://localhost:8000/api/v1/
Content-Type: application/json

{
"task":"learning to code", 
"hr":"15"
}

### get api
PATCH http://localhost:8000/api/v1/
Content-Type: application/json

{
"_id":"605fa7133341104da0f74027",
"todo": false
}

### get api
PUT http://localhost:8000/api/v1//

### get api
GET http://localhost:8000/api/v1/


### get api
DELETE  http://localhost:8000/api/v1/
Content-Type: application/json

{
 "args": ["605fef2bc4f2da3f428fcc4c", "605fef2bc4f2da3f428fcc4d"]
}